### PR TITLE
Allowed Nest.js v10

### PR DESCRIPTION
**Pull request by icetee**

### CODE REVIEW

**Review by lefrancoisjc — APPROVED** [review]
👍

**Comment by lefrancoisjc** [comment]
@lambrohan could you merge this PR ? 🙏

**Review by lambrohan — APPROVED** [review]

**Comment by lambrohan** [comment]
@jclappiway merged

**Comment by lefrancoisjc** [comment]
many thanks  !

**Comment by lefrancoisjc** [comment]
@lambrohan you're sure the release is good ? I got some errors : `Cannot find module 'nestjs-meilisearch' or its corresponding type declarations.`
Meanwhile I fixed it with an `npm run build` inside the node_module but now it's time to CI :P

**Pull request merged**
