### PR TITLE
fix(github): add build step before publishing release

### LINKED ISSUE #13: Release `v2.0.7` ships without package (i.e., `/lib`)
## Reproduction Steps

1. Create a new project and install `nestjs-meilisearch` (v2.0.7)
2. Check `node_modules` directory

## Expected

Transpiled code should be packaged in `lib` directory.

## Actual

`lib` directory is missing in `v2.0.7`.

Screenshot 2024-10-22 at 10 47 35

### PR DESCRIPTION
**Pull request by kylejb**
Fixes #13 

---

### Summary

- [x] Install dependencies from lockfile in CI/CD to ensure consistency when publishing; we should only be modifying lock files in development imo.
- [x] Add build step before publishing

### CODE REVIEW

**Comment by kylejb** [comment]
@lambrohan, you beat me to it with https://github.com/lambrohan/nestjs-meilisearch/commit/25268c92d2925cf7c2e469f2392f0f73a253c620. :)

**Comment by lambrohan** [comment]
ahhh, I think it was happening in parallel 😄!

**Comment by kylejb** [comment]
I recommend we still incorporate installing dependencies from lockfile. I was about to repurpose this PR for that in case you liked the idea.

```yaml
      - run: pnpm install --frozen-lockfile
```

**Comment by kylejb** [comment]
> I recommend we still incorporate installing dependencies from lockfile. I was about to repurpose this PR for that in case you liked the idea.
> 
> ```yaml
>       - run: pnpm install --frozen-lockfile
> ```

FYI – I created https://github.com/lambrohan/nestjs-meilisearch/pull/16 in case you like the idea, @lambrohan.

**Comment by lambrohan** [comment]
merged

**Pull request closed without merging**
